COURSE_MAP = {
    "אוטומטים ושפות פורמליות": "Automata and Formal Languages",
    "אחזור מידע": "Information Retrieval",
    "אינפי א׳": "Calculus 1",
    "אינפי א'": "Calculus 1",
    "אינפי ב'": "Calculus 2",
    "אינפי ב׳": "Calculus 2",
    "אלגברה ליניארית א'": "Linear Algebra 1",
    "אלגברה ליניארית ב'": "Linear Algebra 2",
    "אלקטרוניקה אנלוגית וספרתית": "Analog and Digital Electronics",
    "אנגלית למדעי המחשב": "English for Computer Science",
    "בסיסי נתונים": "Databases",
    "הכרת משאבי הספריה": "Library Resources",
    "הנדסת תוכנה": "Software Engineering",
    "הסתברות": "Probability",
    "חישוביות ומורכבות החישובים": "Computability and Complexity",
    'כריית מידע - למדה"מ': "Data Mining",
    "כריית מידע - למדה\"מ": "Data Mining",
    "לוגיקה מתמטית": "Mathematical Logic",
    "מבוא לאבטחת מידע": "Introduction to Information Security",
    "מבוא לבינה מלאכותית": "Introduction to Artificial Intelligence",
    "מבוא להנדסת תוכנה": "Introduction to Software Engineering",
    "מבוא למדעי המחשב": "Introduction to Computer Science",
    "מבוא לרברסינג": "Introduction to Reverse Engineering",
    "מבוא לתקשורת מחשבים": "Introduction to Computer Networks",
    "מבחנים": "Exams Archive",
    "מבנה המחשב": "Computer Architecture",
    "מבנה נתונים ב'": "Data Structures 2",
    "מבנה נתונים ותוכניות א'": "Data Structures and Programs 1",
    "מבנה שפות תכונה": "Structure of Programming Languages",
    "מיני פרוייקט בבסיסי נתונים": "Mini Project in Databases",
    "מיני פרויקט במערכות חלונות": "Mini Project in Windows Systems",
    "מעבדה במבנה המחשב": "Computer Architecture Lab",
    "מערכות הפעלה": "Operating Systems",
    "מערכות זמן אמת ותכנות מקבילי": "Real-Time Systems and Parallel Programming",
    "מערכות ספרתיות (לוגיקה)": "Digital Systems (Logic)",
    "משדיף": "Differential Equations",
    "מתמטיקה בדידה": "Discrete Mathematics",
    "ניתוח אלגוריתמים וסיבוכיות": "Algorithms and Complexity Analysis",
    "ניתוח מערכות ממוחשבות": "Computerized Systems Analysis",
    "סטטיסטיקה": "Statistics",
    "עיצוב ותכנות מונחי עצמים להנדסה": "Object-Oriented Design and Programming for Engineering",
    "עקרונות שפות תוכנה": "Principles of Programming Languages",
    "פיזיקה": "Physics",
    "קדם במתמטיקה": "Precalculus",
    "קומפיילרים": "Compilers",
    "קורסי רשות": "Elective Courses",
    "רשתות TCP-IP": "TCP/IP Networks",
    "תכון תוכנה": "Software Design",
    "תכנות מונחי עצמים מתקדם": "Advanced Object-Oriented Programming",
    "תכנות פונקציונלי ולוגי": "Functional and Logic Programming",
}

SKIP_TOP_FOLDERS = {
    "עותק של מערכות הפעלה",
}

TYPE_KEYWORDS = (
    (("מבחן", "מבחנים", "exam", "exams", "moed", "מועד", "final", "midterm"), "exams", "exam"),
    (("תרגיל", "תרגילים", "quiz", "exercise", "homework", "assignment", "hw"), "quizzes", "exercise"),
    (("סיכום", "סיכומים", "summary", "notes", "lecture notes"), "summaries", "summary"),
    (("מצגת", "מצגות", "שקף", "שקפים", "slide", "presentation", "ppt"), "presentations", "presentation"),
    (("הרצאה", "הקלטה", "recording", "video", "zoom", "mp4"), "recordings", "recording"),
    (("תרגול", "תרגולים"), "quizzes", "exercise"),
)
